#!/usr/bin/python3
# -*- coding: utf-8 -*-

from bcc import BPF
from bcc.utils import printb

# eBPFのソースをVMに読み取らせる
b = BPF(text="""
#define KBUILD_MODNAME "tcp_probe"
#include <net/ipv6.h>
TRACEPOINT_PROBE(tcp, tcp_probe) {
    // args is from /sys/kernel/debug/tracing/events/tcp/tcp_probe/format
    bpf_trace_printk("%d %d %d\\n", args->daddr[0], args->daddr[1], args->daddr[2]);
    return 0;
}
""")

# ヘッダ出力
print("%-18s %-16s %-6s %s" % ("TIME(s)", "COMM", "PID", "MSG"))

# eBPFからのoutputを受信してプリントアウトするループ
while 1:
    try:
        (task, pid, cpu, flags, ts, msg) = b.trace_fields()
    except ValueError:
        continue
    except KeyboardInterrupt:
        # Ctrl-Cでループから脱出
        exit()
    printb(b"%-18.9f %-16s %-6d %s" % (ts, task, pid, msg))



