#!/usr/bin/python3
# -*- coding: utf-8 -*-

from bcc import BPF
from bcc.utils import printb

# eBPFのVMにロードさせるプログラムのCコードを文字列として定義
bpf_text = """
int kprobe__execve(struct pt_regs *ctx)
{
	bpf_trace_printk("start of execve\\n");
	return 0;
};
"""

# VMに文字列として定義したプログラムをロードさせる
# tracepointへの割り付けは自動(Cコードで「kprobe__execve」を定義)
b = BPF(text=bpf_text)

# ヘッダの出力
print("%-6s %-12s %s" % ("PID", "COMM", "OUTPUT"))

# eBPFの通知を無限ループで順次受けて出力
while 1:
        # Read messages from kernel pipe
        try:
            (task, pid, cpu, flags, ts, msg) = b.trace_fields()
        except ValueError:
            # Ignore messages from other tracers
            continue
        except KeyboardInterrupt:
            # Ctrl-Cでループから脱出
            exit()

        printb(b"%-6d %-12.12s %s" % (pid, task, msg))


